spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080/handletter
    username: root
    password: ${DB_PWD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c0d1e83d168ca9c4f8db1ebc6e56b37f
            client-secret: vkOp9LE28S4JVeuiWfBp31ozoivDSaHc
            client-name: Kakao
            client-authentication-method: POST
            redirect-uri: "http://localhost:3000/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
cloud:
  aws:
    s3:
      bucket: handlatters3
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_ACCESS_PASSWORD}


