spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/handletter
    username: root
    password: ${DB_PWD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c0d1e83d168ca9c4f8db1ebc6e56b37f
            client-secret: vkOp9LE28S4JVeuiWfBp31ozoivDSaHc
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize?prompt=login
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
  jpa:
    hibernate:
      ddl-auto: update
cloud:
  aws:
    s3:
      bucket: handlatters3
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_ACCESS_PASSWORD}

jwt:
  secretKey: secretKeysecretKeysecretKeysecretKeysecretKey
  access:
    expiration: 720000000

